version: '3'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod # "Dockerfile"이 아니라 뒤에 prod가 붙기 때문에 명시적으로 작성
    command: gunicorn --capture-output config.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 -t 300
    environment:
      PYTHONUNBUFFERED: 1
      DJANGO_SETTINGS_MODULE: config.settings.prod # prod.py
    env_file:
      - .env # .github/workflows/deploy.yml에서 만든 env 파일에 의존
    expose:
      - 8000
    entrypoint:
      - sh
      - entrypoint.prod.sh

  nginx:
    container_name: nginx
    build: ./nginx/ # 이 폴더 안에도 Dockerfile이 있고 이 도커파일에서 설정파일인 nginx.conf 파일로 연결시켜준다
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/home/app/web/data/redis

volumes:
  static:
  media:
  redisdata: