version: '3'
services:

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: dstagram
      MYSQL_ROOT_PASSWORD: 1234
    expose:
      - 3306
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  web:
    container_name: web
    build: . # . 은 디폴트 -> 프로젝트 내의 "Dockerfile"이라는 이름을 알아서 찾아 빌드해줌
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000" # 최종 런서버 - 브라우저에서 확인 가능
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      DATABASE_NAME: database
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 1234
      DATABASE_PORT: 3306
      DATABASE_HOST: db
    restart: always
    ports:
      - "8000:8000"
    volumes: # 파일 시스템 정의
      - .:/app
    depends_on: # db 컨테이너로 연결
      - db
volumes:
  app:
  dbdata:
  redisdata: