version: '3'
services:

  db:
    container_name: db
    image: keinos/sqlite3
    environment:
      - SQLITE3_DB=db.dstagram
    volumes: # 파일 시스템 정의
      - ./data/db:/root/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  web:
    container_name: web
    build: . # . 은 디폴트 -> 프로젝트 내의 "Dockerfile"이라는 이름을 알아서 찾아 빌드해줌
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000" # 최종 런서버 - 브라우저에서 확인 가능
    restart: always
    ports:
      - "8000:8000"
    volumes: # 파일 시스템 정의
      - .:/app
    depends_on: # db 컨테이너로 연결
      - db
volumes:
  app:
  dbdata:
  redisdata: