# Generated by Django 3.1 on 2022-05-24 12:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220524_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile_pic/base/empty_user_icon.png', upload_to=accounts.models.User.profile_pic_upload),
        ),
    ]
