# Generated by Django 3.1 on 2022-06-16 00:57

import accounts.models
import config.asset_storage
from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220611_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=django_fields.fields.DefaultStaticImageField(blank=True, storage=config.asset_storage.ProfileStorage(), upload_to=accounts.models.User.profile_pic_upload),
        ),
    ]
