# Generated by Django 3.1 on 2022-06-13 10:02

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
