# Generated by Django 3.1 on 2022-05-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20220531_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='photo',
            new_name='post',
        ),
    ]
